name: Lint

on: 
    workflow_dispatch:
    push:
        branches: [main]

jobs:
    lint-check:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install pylint
              run: |
                python -m pip install --upgrade pip
                pip install pylint
            - name: Run pylint
              run: |
                find . -name '*.py' -exec pylint {} \;
